FROM node:16-alpine

USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install -g npm@8.6.0
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]
